In [1]:
import numpy as np

In [2]:
x = [21, 23, 27, 32, 34, 41, 50, 53, 57, 59, 38, 46, 48, 48, 60]
y = [1000, 1100, 1250, 1700, 1500, 1980, 2500, 3500, 2200, 4100, 3900, 5100, 5500, 7000, 6500]

In [3]:
import plotly.express as px

In [4]:
grafico = px.scatter(x=x, y=y)
grafico.show()

In [5]:
base_salario = np.array([[21,100],[23,1100],[27,1250],[32,1700],[34,1500],[41,1980],[38,3900],[46,5100],
[46,500],[48,7000],[53,3500],[57,2200],[59,4100],[60,6500],[60,2500]])

In [6]:
base_salario

array([[  21,  100],
       [  23, 1100],
       [  27, 1250],
       [  32, 1700],
       [  34, 1500],
       [  41, 1980],
       [  38, 3900],
       [  46, 5100],
       [  46,  500],
       [  48, 7000],
       [  53, 3500],
       [  57, 2200],
       [  59, 4100],
       [  60, 6500],
       [  60, 2500]])

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [9]:
base_salario

array([[-1.68931157, -1.36021996],
       [-1.53573779, -0.86774351],
       [-1.22859023, -0.79387204],
       [-0.84465579, -0.57225764],
       [-0.69108201, -0.67075293],
       [-0.15357378, -0.43436423],
       [-0.38393445,  0.51119056],
       [ 0.23036067,  1.1021623 ],
       [ 0.23036067, -1.16322938],
       [ 0.38393445,  2.03786755],
       [ 0.7678689 ,  0.31419998],
       [ 1.07501645, -0.32601941],
       [ 1.22859023,  0.60968585],
       [ 1.30537712,  1.79162933],
       [ 1.30537712, -0.17827647]])

In [10]:
from sklearn.cluster import KMeans

In [11]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [12]:
centroide = kmeans_salario.cluster_centers_
centroide

array([[ 0.38393445,  1.36071243],
       [ 1.09421318,  0.10489748],
       [-0.84465579, -0.83749138]])

In [13]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  48.        , 5625.        ],
       [  57.25      , 3075.        ],
       [  32.        , 1161.42857143]])

In [14]:
rotulos = kmeans_salario.labels_
rotulos

array([2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 1, 1, 0, 1])

In [16]:
import plotly.graph_objects as go
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=rotulos)
grafico2 = px.scatter(x = centroide[:,0], y=centroide[:,1])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()